/*
 * Copyright (c) 2025-2026 ADA Lab, Soochow University
 */

/**
 * export_config — DARE grid search (upper) + TS-MDP per-region fanout (lower).
 *
 * Usage (WSL2):
 *   ./build/export_config <pdf_file> <dataset_file> <output_json>
 *
 *   pdf_file:     global PDF(16384) for DARE, generated by gen_pdf.py
 *   dataset_file: binary .data file (key-value pairs) for per-region TS-MDP
 *   output_json:  { rootFanOut, innerFanouts[rootFanOut] }
 */
#include "../include/RL_network.hpp"
#include "../include/experience.hpp"
#include "../../include/DEFINE.h"
#include "../../include/DataSet.hpp"

#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cmath>
#include <algorithm>

using kv_pair = std::pair<double, double>;

// ── PDF I/O ──

std::vector<float> read_pdf(const std::string& path) {
    std::vector<float> pdf;
    std::ifstream file(path);
    float val;
    while (file >> val) pdf.push_back(val);
    if (pdf.size() != PDF_SIZE) {
        std::cerr << "Warning: PDF has " << pdf.size()
                  << " entries, expected " << PDF_SIZE << std::endl;
        pdf.resize(PDF_SIZE, 0.0f);
    }
    return pdf;
}

// ── Local PDF for TS-MDP (matches C++ get_pdf in DataSet.hpp) ──

std::vector<float> local_pdf(const std::vector<kv_pair>& data,
                              int left, int right,
                              double lo, double hi, int pdf_size) {
    std::vector<float> bucket(pdf_size, 0.0f);
    int n = right - left;
    if (n == 0 || hi <= lo) return bucket;

    double range = hi - lo;
    for (int i = left; i < right; i++) {
        int idx = std::min(pdf_size - 1,
            std::max(0, (int)(pdf_size * (data[i].first - lo) / range)));
        bucket[idx] += 1.0f / n;
    }
    return bucket;
}

// ── TS-MDP per-region ──

std::vector<int> tsmdp_per_region(
    const std::vector<kv_pair>& sorted_data,
    double key_min, double key_max,
    int root_fanout,
    std::shared_ptr<Small_Q_network>& q_net)
{
    std::vector<int> inner_fanouts(root_fanout, 1);
    int n = int(sorted_data.size());

    // Count keys per root bucket
    std::vector<int> root_counts(root_fanout, 0);
    double range = key_max > key_min ? key_max - key_min : 1.0;
    for (auto& kv : sorted_data) {
        int slot = std::min(root_fanout - 1,
            std::max(0, (int)(root_fanout * (kv.first - key_min) / range)));
        root_counts[slot]++;
    }

    int left = 0;
    for (int r = 0; r < root_fanout; r++) {
        int right = left + root_counts[r];
        int data_count = root_counts[r];

        if (data_count <= 1) {
            inner_fanouts[r] = 1;
            left = right;
            continue;
        }

        double lo = key_min + range * r / root_fanout;
        double hi  = key_min + range * (r + 1) / root_fanout;

        if (data_count <= 5 || q_net == nullptr) {
            // Heuristic
            if (data_count <= 10)          inner_fanouts[r] = 1;
            else if (data_count <= 50)     inner_fanouts[r] = 2;
            else if (data_count <= 200)    inner_fanouts[r] = 4;
            else if (data_count <= 1000)   inner_fanouts[r] = 8;
            else if (data_count <= 5000)   inner_fanouts[r] = 16;
            else if (data_count <= 20000)  inner_fanouts[r] = 32;
            else if (data_count <= 100000) inner_fanouts[r] = 64;
            else                           inner_fanouts[r] = 128;
        } else {
            // TS-MDP: batch-evaluate all actions
            auto pdf = local_pdf(sorted_data, left, right, lo, hi, SMALL_PDF_SIZE);
            int na = int(action_space.size());

            auto a = torch::tensor(pdf).view({1, SMALL_PDF_SIZE}).mul(
                torch::ones({na, SMALL_PDF_SIZE})).to(GPU_DEVICE);
            auto b = torch::tensor(float(data_count)).view({1, 1}).mul(
                torch::ones({na, 1})).to(GPU_DEVICE);
            auto c = torch::tensor(action_space).to(torch::kFloat32)
                .view({na, 1}).to(GPU_DEVICE);

            torch::Tensor pred;
            {
                torch::NoGradGuard no_grad;
                pred = q_net->forward(a, b, c).to(CPU_DEVICE);
            }

            auto ac_id = torch::argmax(pred, 0).item().toInt();
            inner_fanouts[r] = 1 << ac_id;
        }

        left = right;
    }

    return inner_fanouts;
}

// ── JSON output ──

void write_json(const std::string& path, float rootFanOut,
                const std::vector<int>& innerFanouts) {
    std::ofstream out(path);
    out << "{\n";
    out << "  \"rootFanOut\": " << rootFanOut << ",\n";
    out << "  \"innerFanouts\": [";
    for (size_t i = 0; i < innerFanouts.size(); i++) {
        if (i > 0) out << ",";
        if (i % 16 == 0) out << "\n    ";
        out << innerFanouts[i];
    }
    out << "\n  ]\n";
    out << "}\n";
    out.close();
}

// ── Main ──

int main(int argc, char* argv[]) {
    if (argc < 4) {
        std::cerr << "Usage: export_config <pdf_file> <dataset_file> <output_json>" << std::endl;
        return 1;
    }
    std::string pdf_path     = argv[1];
    std::string dataset_path = argv[2];
    std::string output_path  = argv[3];

    // ═══════════════════════════════════════════════
    // 1. Load Global_Q_network (DARE)
    // ═══════════════════════════════════════════════
    std::cout << "Loading Global_Q_network..." << std::endl;
    auto q_model = std::make_shared<Global_Q_network>(Global_Q_network());
    q_model->eval();
    q_model->to(GPU_DEVICE);
    auto scalar = std::make_shared<RewardScalar>(RewardScalar(2));

    if (IsFileExist(q_model_path.c_str())) {
        torch::load(q_model, q_model_path);
        scalar->load(q_scalar_path);
        q_model->to(GPU_DEVICE);
        std::cout << "  loaded: " << q_model_path << std::endl;
    } else {
        std::cerr << "Model not found: " << q_model_path << std::endl;
        return 1;
    }

    // ═══════════════════════════════════════════════
    // 2. DARE grid search → best rootFanOut
    // ═══════════════════════════════════════════════
    std::vector<float> pdf = read_pdf(pdf_path);
    std::cout << "PDF loaded: " << pdf.size() << " entries" << std::endl;

    float root_candidates[] = {8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096};
    float inner_candidates[] = {2, 4, 8, 16, 32, 64, 128};
    const int n_root  = sizeof(root_candidates) / sizeof(root_candidates[0]);
    const int n_inner = sizeof(inner_candidates) / sizeof(inner_candidates[0]);
    int batch = n_root * n_inner;

    std::vector<float> batch_pdf(batch * PDF_SIZE);
    std::vector<float> batch_data_size(batch, 1.0f);
    std::vector<float> batch_root(batch);
    std::vector<float> batch_inner(batch * INNER_FANOUT_COLUMN);
    std::vector<float> output(batch * REWARD_SIZE);

    int idx = 0;
    for (int r = 0; r < n_root; r++) {
        for (int ii = 0; ii < n_inner; ii++) {
            std::copy(pdf.begin(), pdf.end(), batch_pdf.begin() + idx * PDF_SIZE);
            batch_root[idx] = root_candidates[r];
            for (int j = 0; j < INNER_FANOUT_COLUMN; j++)
                batch_inner[idx * INNER_FANOUT_COLUMN + j] = inner_candidates[ii];
            idx++;
        }
    }

    std::cout << "DARE evaluating " << batch << " candidates..." << std::endl;
    {
        auto pdf_t  = torch::from_blob(batch_pdf.data(), {batch, PDF_SIZE},
                                       torch::kFloat32).to(GPU_DEVICE);
        auto val_t  = torch::from_blob(batch_data_size.data(), {batch, 1},
                                       torch::kFloat32).to(GPU_DEVICE);
        auto root_t = torch::from_blob(batch_root.data(), {batch, 1},
                                       torch::kFloat32).to(GPU_DEVICE);
        auto inner_t= torch::from_blob(batch_inner.data(),
                                       {batch, INNER_FANOUT_ROW, INNER_FANOUT_COLUMN},
                                       torch::kFloat32).to(GPU_DEVICE);

        torch::Tensor pred;
        {
            torch::NoGradGuard no_grad;
            pred = q_model->forward(pdf_t, val_t, root_t, inner_t);
            pred = scalar->inverse(pred).to(CPU_DEVICE);
        }
        std::memcpy(output.data(), pred.data_ptr<float>(),
                    batch * REWARD_SIZE * sizeof(float));
    }

    int best_idx = 0;
    float best_cost = std::numeric_limits<float>::max();
    for (int i = 0; i < batch; i++) {
        float mem_cost = output[i * REWARD_SIZE];
        float get_cost = output[i * REWARD_SIZE + 1];
        float cost = mem_cost * MEMORY_WEIGHT + get_cost * QUERY_WEIGHT;
        if (cost < best_cost) { best_cost = cost; best_idx = i; }
    }

    int best_r = best_idx / n_inner;
    int best_i = best_idx % n_inner;
    int rootFanOut = (int)root_candidates[best_r];
    int dareInner  = (int)inner_candidates[best_i];
    std::cout << "DARE best: rootFanOut=" << rootFanOut
              << " innerFanOut=" << dareInner
              << " cost=" << best_cost << std::endl;

    // ═══════════════════════════════════════════════
    // 3. Load Small_Q_network (TS-MDP)
    // ═══════════════════════════════════════════════
    std::shared_ptr<Small_Q_network> small_q = nullptr;
    std::string tmp_pt_path = model_father_path + "tmp.pt";
    if (IsFileExist(tmp_pt_path.c_str())) {
        small_q = std::make_shared<Small_Q_network>();
        torch::load(small_q, tmp_pt_path);
        small_q->to(GPU_DEVICE);
        small_q->eval();
        std::cout << "Small_Q loaded: " << tmp_pt_path << std::endl;
    } else {
        std::cout << "Small_Q not found at " << tmp_pt_path
                  << " — using heuristic fallback" << std::endl;
    }

    // ═══════════════════════════════════════════════
    // 4. Load dataset & compute per-region TS-MDP
    // ═══════════════════════════════════════════════
    std::vector<int> innerFanouts;

    if (IsFileExist(dataset_path.c_str())) {
        auto dataset = dataset_source::get_dataset<kv_pair>(dataset_path);
        std::cout << "Dataset loaded: " << dataset.size() << " entries" << std::endl;

        // Sample if too large
        size_t max_sample = 10'000'000;
        if (dataset.size() > max_sample) {
            dataset.resize(max_sample);
            std::cout << "  (sampled down to " << max_sample << ")" << std::endl;
        }

        std::sort(dataset.begin(), dataset.end(),
            [](const kv_pair& a, const kv_pair& b) { return a.first < b.first; });

        double key_min = dataset.front().first;
        double key_max = dataset.back().first;
        std::cout << "Key range: [" << key_min << ", " << key_max << "]" << std::endl;

        innerFanouts = tsmdp_per_region(dataset, key_min, key_max,
                                         rootFanOut, small_q);
    } else {
        std::cout << "Dataset not found: " << dataset_path
                  << " — using DARE uniform innerFanout=" << dareInner << std::endl;
        innerFanouts.assign(rootFanOut, dareInner);
    }

    size_t fanout_distinct = 0;
    {
        auto sorted = innerFanouts;
        std::sort(sorted.begin(), sorted.end());
        fanout_distinct = std::unique(sorted.begin(), sorted.end())
                          - sorted.begin();
    }
    std::cout << "TS-MDP innerFanouts: " << innerFanouts.size()
              << " regions, " << fanout_distinct << " distinct fanouts" << std::endl;

    // ═══════════════════════════════════════════════
    // 5. Write JSON
    // ═══════════════════════════════════════════════
    write_json(output_path, (float)rootFanOut, innerFanouts);
    std::cout << "Config written to: " << output_path << std::endl;

    return 0;
}
